terrela_app/models.py
"""Create database models to represent tables."""
from terrela_app import db
from sqlalchemy.orm import backref
from flask_login import UserMixin


class User(UserMixin, db.Model):
    """Users model."""
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)

    def __repr__(self):
        return f'<User: {self.username}>'

class Missions(db.Model):
    """Missions model."""
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), nullable=False, unique=True)
    date = db.Column(db.Date)
    description = db.Column(db.String(500))
    rocket_id = db.Column(db.Integer, db.ForeignKey('rockets.id'))
    rocket = db.relationship('Rockets', back_populates='missions')

class Rockets(db.Model):
    """Rockets model."""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False, unique=True)
    description = db.Column(db.String(500))
    missions = db.relationship('Missions', back_populates='rocket')

class AstronomicalObjects(db.Model):
    """Astronomical Objects model."""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    category = db.Column(db.String(100), nullable=False)
    description = db.Column(db.String(500))

terrela_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, DateField
from wtforms.validators import DataRequired, Length, ValidationError
from terrela_app.models import Missions, Rockets, AstronomicalObjects

class MissionForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(max=80)])
    date = DateField('Date Launch', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[Length(max=500)])
    submit = SubmitField('Submit')

class RocketsForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(max=100)])
    description = TextAreaField('Description', validators=[Length(max=500)])
    submit = SubmitField('Submit')

class AstronomicalObjectsForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(max=100)])
    category = StringField('Category', validators=[DataRequired(), Length(max=100)])
    description = TextAreaField('Description', validators=[Length(max=500)])
    submit = SubmitField('Submit')

terrela_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from terrela_app.config import Config
import os

app = Flask(__name__)
app.config.from_object(Config)
app.secret_key = os.urandom(24)

db = SQLAlchemy(app)

#####################################
#           Authentication          #
#####################################

login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)

from .models import User

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

bcrypt = Bcrypt(app)

#####################################
#           Blueprints              #
#####################################

from terrela_app.main.routes import main
app.register_blueprint(main)

from terrela_app.auth.routes import auth
app.register_blueprint(auth)

with app.app_context():
    db.create_all()

terrela_app/main/routes.py
"""Import packages and modules."""
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from datetime import date, datetime
from terrela_app.models import User, Missions, Rockets, AstronomicalObjects
from terrela_app.main.forms import MissionForm, RocketsForm, AstronomicalObjectsForm
from terrela_app import bcrypt

# Import app and db from events_app package so that we can run app
from terrela_app import app, db

main = Blueprint("main", __name__)

##########################################
#           Routes                       #
##########################################

@main.route('/',  methods=['GET', 'POST'])
def homepage():
    all_missions = Missions.query.all()
    all_rockets = Rockets.query.all()
    all_objects = AstronomicalObjects.query.all()
    print(f'Missions: {all_missions}')
    print(f'Rockets: {all_rockets}')
    print(f'Objects: {all_objects}')

    return render_template('home.html')

@main.route('/create_mission', methods=['GET', 'POST']) # VERIFICAR ROCKET_ID!!!
def create_mission():
    form = MissionForm()

    if form.validate_on_submit():
        new_mission = Missions(
            title=form.title.data,
            date=form.date.data,
            description=form.description.data
        )
        db.session.add(new_mission)
        db.session.commit()

        flash('New mission was created successfully.')
        return redirect(url_for('main.mission_detail'))
    return render_template('create_mission.html', form=form)

@main.route('/mission_details', methods=['GET', 'POST'])
def mission_detail():

    return render_template('mission_detail.html')

@main.route('/create_object', methods=['GET', 'POST'])
def create_object():
    form = AstronomicalObjectsForm()

    if form.validate_on_submit():
        new_object = AstronomicalObjects(
            name=form.name.data,
            category=form.category.data,
            description=form.description.data
        )
        db.session.add(new_object)
        db.session.commit()

        flash('New object was created successfully.')
        return redirect(url_for('main.object_details', object_id=new_object.id))
    return render_template('create_object.html', form=form)

@main.route('/object_details/<object_id>', methods=['GET', 'POST'])
def object_details(object_id):
    astronomical_object = AstronomicalObjects.query.get(object_id)
    form = AstronomicalObjectsForm(obj=astronomical_object)

    if form.validate_on_submit():
        astronomical_object.name = form.name.data,
        astronomical_object.category = form.category.data,
        astronomical_object.description = form.description.data

        db.session.add(astronomical_object)
        db.session.commit()

        flash('Object was edited successfully')
        return redirect(url_for('main.object_detail', object_id=astronomical_object.id))

    return render_template('object_detail.html', object=astronomical_object, form=form)

@main.route('/create_rocket', methods=['GET', 'POST'])
def create_rocket():
    form = RocketsForm()

    if form.validate_on_submit():
        new_rocket = Rockets(
            name=form.name.data,
            description=form.description.data,
        )
        db.session.add(new_rocket)
        db.session.commit()

        flash('New object was created successfully.')
        return redirect(url_for('main.rocket_details', rocket_id=new_rocket.id))
    return render_template('create_rocket.html', form=form)

@main.route('/rocket_details/<rocket_id>', methods=['GET', 'POST'])
def rocket_details(rocket_id):
    rocket = Rockets.query.get(rocket_id)
    form = RocketsForm(obj=rocket)

    if form.validate_on_submit():
        rocket.name = form.name.data,
        rocket.description = form.description.data,
        rocket.mission = form.mission.data

        db.session.add(rocket)
        db.session.commit()

        flash('Object was edited successfully')
        return redirect(url_for('main.rocket_detail', rocket_id=rocket.id))

    return render_template('rocket_detail.html', rocket=rocket, form=form)

@main.route('/example', methods=['GET', 'POST'])
def base():
    return render_template('example.html')

terrela_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename = 'css/styles.css')}}">
    <link rel="shortcut icon" type="image/png" href="./resources/images/favicons.png">
    <title>Terrela{% block title %}{% endblock %}</title>
</head>
<body>
    {% for message in get_flashed_messages() %}
    <p class="text-center">{{ message }}</p>
    {% endfor %}    
    {% block content %}{% endblock %}
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

terrela_app/templates/create_mission.html
{% extends 'base.html' %}

{% block content %}

<div class="container p-5">
    <p class="fs-1">Add a mission</p>
</div>
<div class="container p-5 ">
    <div class="row p-5">
        <div class="col offset-4">
            <form class="p-4" method="POST" action="{{ url_for('main.create_mission') }}">
                {{ form.csrf_token }}
                <div class="mb-3">
                    <div class="container">{{ form.title.label }}</div>
                    <div class="container">{{ form.title }}</div>
                    <ul>
                        {% for error in form.title.errors %}
                        <li class="error">{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="mb-3">
                    <div class="container">{{ form.date.label }}</div>
                    <div class="container">{{ form.date }}</div>
                    <ul>
                        {% for error in form.date.errors %}
                        <li class="error">{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="mb-3">
                    <div class="container">{{ form.rocket_id.label }}</div>
                    <div class="container">{{ form.rocket_id }}</div>
                    <ul>
                        {% for error in form.rocket_id.errors %}
                        <li class="error">{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="mb-3">
                    <div class="container">{{ form.description.label }}</div>
                    <div class="container">{{ form.description }}</div>
                    <ul>
                        {% for error in form.description.errors %}
                            <li class="error">{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="container">{{ form.submit }}</div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

terrela_app/templates/create_object.html
{% extends 'base.html' %}

{% block content %}
<div class="container p-5">
    <p class="fs-1">Add an object</p>
</div>
<div class="container p-5 ">
    <div class="row p-5">
        <div class="col offset-4">
            <form class="p-4" method="POST" action="{{ url_for('main.create_object') }}">
                {{ form.csrf_token }}
                <div class="mb-3">
                    <div class="container">{{ form.name.label }}</div>
                    <div class="container">{{ form.name }}</div>
                    <ul>
                        {% for error in form.name.errors %}
                        <li class="error">{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="mb-3">
                    <div class="container">{{ form.category.label }}</div>
                    <div class="container">{{ form.category }}</div>
                    <ul>
                        {% for error in form.category.errors %}
                        <li class="error">{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="mb-3">
                    <div class="container">{{ form.description.label }}</div>
                    <div class="container">{{ form.description }}</div>
                    <ul>
                        {% for error in form.description.errors %}
                        <li class="error">{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="container">{{ form.submit }}</div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

terrela_app/templates/create_rocket.html
{% extends 'base.html' %}

{% block content %}

<div class="container p-5">
    <p class="fs-1">Add rocket</p>
</div>
<div class="container p-5 ">
    <div class="row p-5">
        <div class="col offset-4">
            <form class="p-4" method="POST" action="{{ url_for('main.create_rocket') }}">
                {{ form.csrf_token }}
                <div class="mb-3">
                    <div class="container">{{ form.name.label }}</div>
                    <div class="container">{{ form.name }}</div>
                    <ul>
                        {% for error in form.name.errors %}
                        <li class="error">{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="mb-3">
                    <div class="container">{{ form.description.label }}</div>
                    <div class="container">{{ form.description }}</div>
                    <ul>
                        {% for error in form.description.errors %}
                        <li class="error">{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="container">{{ form.submit }}</div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

terrela_app/templates/example.html
<!DOCTYPE html>
<html>
    <head>
        <title>Solar System</title>
        <link rel="stylesheet" href="{{url_for('static',filename = 'css/styles.css')}}">
        <link rel="shortcut icon" type="image/png" href="./resources/images/favicons.png">

    </head>
    <body>
        <div id="gigantic-container">
            <div id="left-section-container">
                <div id="left-section-upper-container">
                    <a href="#solar-system">
                        <h1 id="solar-system-text">Solar System</h1>
                    </a>
                    <div id="solar-system-description-container">
                        <p id="solar-system-description">The solar system is a gravitationally bound system around the Sun. From the objects that orbit the Sun directly, there are two main categories: Inner Planets and Outer Planets. The four smaller inner planets, Mercury, Venus, Earth and Mars are terrestrial planets. In the outer planets there are the two largest planets, Jupiter and Saturn, gas giants, and the two outermost plantes Uranus and Neptune, which are ice giants.</p>
                    </div>
                </div>
                <nav id="inner-outer-navigator">
                    <ul id="inner-outer-ul">
                        <li id="inner-link" class="inner-outer-li">
                            <a href="#yellow-dwarf" class="inner-outer-link">
                                <span id="inner-solar-system-text">Yellow dwarf</span>
                            </a>
                        </li>
                        <li id="inner-link" class="inner-outer-li">
                            <a href="#inner-planets-title-container" class="inner-outer-link">
                                <span id="inner-solar-system-text">Inner Solar System</span>
                            </a>
                        </li>
                        <li id="outer-link" class="inner-outer-li">
                            <a href="#outer-planets-title-container" class="inner-outer-link">
                                <span id="outer-solar-system-text">Outer Solar System</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>


            <div id="middle-section-container">
                <div id="middle-section-planets-workspace">
                    <div class="middle-section-title-container" id="yellow-dwarf">
                        <h2>Yellow Dwarf</h2>
                    </div>
                    <div id="inner-planets-clip-board" class="planets-clipboard">
                        <a class="article-link-selection" href="#sun">
                            <div class="inner-planet planet sund-card">
                                <h3>Sun</h3>
                            </div>
                        </a>
                    </div>

                    <div class="middle-section-title-container" id="inner-planets-title-container">
                        <h2>Inner System</h2>
                    </div>
                    <div class="planets-clipboard">
                        <a class="article-link-selection" href="#mercury">
                            <div class="inner-planet planet" id="mercury-card">
                                <h3>Mercury</h3>
                            </div>
                        </a>
                        <a class="article-link-selection" href="#venus">
                            <div class="inner-planet planet" id="venus-card">
                                <h3>Venus</h3>
                            </div>
                        </a>                        
                        <a class="article-link-selection" href="#earth">
                            <div class="inner-planet planet" id="earth-card">
                                <h3>Earth</h3>
                            </div>
                        </a>
                        <a class="article-link-selection" href="#mars">
                             <div class="inner-planet planet" id="mars-card">
                                 <h3>Mars</h3>
                             </div>
                         </a> 
                    </div>

                    <div class="middle-section-title-container" id="outer-planets-title-container">
                        <h2>Outer System</h2>
                    </div>
                    <div class="planets-clipboard">
                         <a class="article-link-selection" href="#jupiter">
                             <div class="outer-planet planet" id="jupiter-card">
                                 <h3>Jupiter</h3>
                           </div>
                        </a>
                        <a class="article-link-selection" href="#saturn">
                            <div class="outer-planet planet" id="saturn-card">
                                <h3>Saturn</h3>
                            </div>
                        </a>
                         <a class="article-link-selection" href="#uranus">
                            <div class="outer-planet planet" id="uranus-card">
                                <h3>Uranus</h3>
                            </div>
                        </a>
                         <a class="article-link-selection" href="#neptune">
                            <div class="outer-planet planet" id="neptune-card">
                                <h3>Neptune</h3>
                            </div>
                        </a>
                    </div>
                </div>
            </div>


            <main id="right-section-container">
                    <!-- Each Article will go here -->
            </main> 

            <!-- If you are going to have the middle part to be scrollable complete the bottom section and upper section div to make the text desapear gradually. -->
            <!-- <div id="middle-bottom-section"></div> -->
            <!-- <div id="middle-upper-section"></div> -->
        </div>

        <script src="{{url_for('static',filename = 'js/scripts.js')}}" type="module">
        </script>
    </body>
</html>

terrela_app/templates/home.html
{% extends 'base.html' %}

{% block title %} | Home{% endblock %}

{% block content %}
        <div id="gigantic-container">
            <div id="left-section-container">
                <div id="left-section-upper-container">
                    <a href="#title-text">
                        <h1 id="title-text">Title</h1>
                    </a>
                    <div id="title-description-container">
                        <p id="title-description">Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim neque quaerat fuga unde voluptates vero, aspernatur dolor, temporibus quod iusto facere! Obcaecati molestias voluptas vel voluptatum culpa unde officiis necessitatibus!</p>
                    </div>
                    <nav id="category-navigator">
                        <ul id="category-ul">
                            {% for i in range(3) %} <!-- Inside of the range is the number of categories -->
                                <li class="category-li">
                                    <a href="#category-{{i+1}}" class="category-link">
                                        <span>Category {{i+1}}</span>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </nav>
                </div>

                <div class="bottom-left-container">
                    <ul id="ul">
                        {% if current_user.is_authenticated %}
                            <a href="/create_mission"><li>Add Mission</li></a>
                            <a href="/create_rocket"><li>Add Rocket</li></a>
                            <a href="/create_object"><li>Add Object</li></a>
                            <a href="/logout"><li>Log Out</li></a>
                        {% else %}
                            <!-- Only show these links if the current user is NOT
                            authenticated (logged in)! -->
                            <a href="/login"><li>Log In</li></a>
                            <a href="/signup"><li>Sign Up</li></a>
                        {% endif %}
                    </ul>
                </div>
                
            </div>
            

            <div id="middle-section-container">
                <div id="middle-section-workspace">

                    {% for i in range(3) %}
                    <div class="middle-section-title-container" id="category-{{i+1}}">
                        <h2>Category {{i+1}}</h2>
                    </div>
                        
                        {% for j in range(4) %}     <!--    list = [1, 4, 4] |||||  for j in range(list[i]) |||||  Assume you have a list of every items you need to make for each category -->
                            <div class="example-clipboard">
                                <a class="article-link-selection" href="#category-{{i+1}}-example-{{j+1}}">
                                    <div class="example">
                                        <h3>Example {{j+1}}</h3>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                    {% endfor %}

                </div>
            </div>

            <main id="right-section-container">
                {% for i in range(3) %}
                    {% for j in range(4) %}     <!--    list = [1, 4, 4] |||||  for j in range(list[i]) |||||  Assume you have a list of every items you need to make for each category -->
                        <article class="right-section-container-article" id="category-{{i+1}}-example-{{j+1}}">
                            <div class="object-name">
                                <h4 class="name-text">Category {{i+1}}: Example {{j+1}}</h4>
                            </div>
                            <div class="right-upper-section-container">
                                <img src="" alt="Category 1: Example">
                            </div>
                            <div class="right-lower-section-container">
                                <div class="information-card-container">
                                    <div class="information-card-text">
                                        <h6 class="quick-facts-text">Quick Facts</h6>
                                    </div>
                                    <div class="information-card-clipboard">
                                        {% for i in range(16) %}
                                            <div class="quick-fact">
                                                <header class="fact-header">
                                                    <h6 class="fact-name">Lorem, ipsum.</h6>
                                                </header>
                                                <div class="fact-description-container">
                                                    <p class="fact-description">Lorem.</p>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <div class="object-description">
                                        <h5 class="object-description-text">Description</h5>
                                    </div>
                                    <div class="paragraph-container">
                                        <p class="paragraph-1">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tenetur rerum omnis alias officiis pariatur ipsam!</p>
                                        <p class="paragraph-2">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Possimus dolor laborum praesentium voluptatum, corrupti facere asperiores quas!</p>
                                        <p class="paragraph-3">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dicta, natus?</p>
                                    </div>
                                </div>
                            </div>
                        </article>
                    {% endfor %}
                {% endfor %}
            </main>
        </div>
{% endblock %}

terrela_app/templates/object_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Astronomical Object - {{ object.name }}</h1>

<p><strong>Category:</strong> {{ object.category }}</p>

<p><strong>Description:</strong> {{ object.description }}</p><br><br><br>


<h2>Edit Store</h2><br>

<form method="POST" action="{{ url_for('main.object_details', object_id=object.id) }}">
    {{ form.csrf_token }}
    <fieldset>
        <div class="mb-3">
            <div class="container">{{ form.name.label }}</div>
            <div class="container">{{ form.name }}</div>
            <ul>
                {% for error in form.name.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="mb-3">
            <div class="container">{{ form.category.label }}</div>
            <div class="container">{{ form.category }}</div>
            <ul>
                {% for error in form.category.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="mb-3">
            <div class="container">{{ form.description.label }}</div>
            <div class="container">{{ form.description }}</div>
            <ul>
                {% for error in form.description.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="container">{{ form.submit }}</div>
    </fieldset>
</form>

{% endblock %}

terrela_app/templates/rocket_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Rocket - {{ rocket.name }}</h1>

<p><strong>Description:</strong> {{ rocket.description }}</p><br><br><br>


<h2>Edit Rocket</h2><br>

<form method="POST" action="{{ url_for('main.rocket_details', rocket_id=rocket.id) }}">
    {{ form.csrf_token }}
    <fieldset>
        <div class="mb-3">
            <div class="container">{{ form.name.label }}</div>
            <div class="container">{{ form.name }}</div>
            <ul>
                {% for error in form.name.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="mb-3">
            <div class="container">{{ form.description.label }}</div>
            <div class="container">{{ form.description }}</div>
            <ul>
                {% for error in form.description.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="container">{{ form.submit }}</div>
    </fieldset>
</form>

{% endblock %}

terrela_app/templates/signup.html
{% extends 'base.html' %}

{% block title%} | Sign Up{% endblock %}

{% block content %}
<div class="container p-5">
    <p class="fs-1">Sign Up</p>
</div>
<div class="container p-5 ">
    <div class="row p-5">
        <div class="col offset-4">
            <form class="p-4" action="/signup" method="POST">
                {{ form.csrf_token }}
                <div class="mb-3">
                    <div class="container">{{ form.username.label }}</div>
                    <div class="container">{{ form.username }}</div>
                    <ul>
                        {% for error in form.username.errors %}
                        <li class="error">{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="mb-3">
                    <div class="container">{{ form.password.label }}</div>
                    <div class="container">{{ form.password }}</div>
                    <ul>
                        {% for error in form.password.errors %}
                            <li class="error">{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="container">{{ form.submit }}</div>
            </form>
        </div>
    </div>
</div>
  {% endblock %}